[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = """\
    --strict-config
    --strict-markers
    """
DJANGO_SETTINGS_MODULE = "tests.settings"
django_find_project = "false"
